gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'gallery'
urlpatterns = [
    path('', views.showGallery, name='showGallery'),
    path('<str:img_uid>/', views.showImage, name='showImage'),
]

picaso/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "picaso"
urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', include('gallery.urls')),
    path('logout/', views.logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

feature/models.py
from django.db import models

# Create your models here.
class Switch(models.Model):
    feature_name = models.CharField(max_length=100)
    toggle = models.BooleanField(default=False)
    feature_desc = models.TextField()

    def __str__(self):
        return "{feature_name} ==> {toggle}".format(feature_name=self.feature_name, toggle = self.toggle)

gallery/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Image(models.Model):
    img_uid = models.CharField(max_length=11)
    img_prompt = models.TextField()
    creation_date = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.img_uid

class JoinTable(models.Model):
    img = models.ForeignKey(Image, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



            

gallery/forms.py
from django import forms

class promtForm(forms.Form):
    prompt = forms.CharField(label="", widget=forms.Textarea(attrs={"rows":5, "cols":50}))

feature/views.py
from django.shortcuts import render

# Create your views here.

gallery/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .models import Image, JoinTable
from django.contrib.auth.models import User

from .forms import promtForm
from feature.models import Switch
from .image_gen import ImageGen

from django.conf import settings

from .awsS3 import AwsManager

import logging
logger = logging.getLogger('watchtower-logger')

# Create your views here.
@login_required(login_url='/', redirect_field_name=None)
def showGallery(request):
    logger.info("Show Gallery Request")
    if request.method == 'GET':
        imageObjects = None
        bypassOpenAISwitch = Switch.objects.get(feature_name = 'bypass_openai').toggle
        form = promtForm() if not bypassOpenAISwitch else None
        try:
            imageObjects = Image.objects.filter(jointable__user = User.objects.get(username = request.user.username))
            logger.info("Fetched Image Objects")
        except Exception as exp: 
            logger.error(f"Got Expcetion {exp}")
        context = {
            'form': form,
        'bypassOpenAISwitch': bypassOpenAISwitch,
            'imageObjects': imageObjects,
            'AWS_STORAGE_BUCKET_URL': settings.AWS_STORAGE_BUCKET_URL,
        }
        return render(request, 'gallery/showGallery.html', context)
    elif request.method == 'POST':
        form = promtForm(request.POST)
        if form.is_valid():
            logger.info("Form is valid")
            prompt = form.cleaned_data['prompt']

            img_uid = ImageGen(prompt).execute()

            # Creating the Image Record and JoinTable Record
            imgObj = Image(img_uid = img_uid, img_prompt = prompt)
            imgObj.save()
            logger.info("Saved image object")
            jtObj = JoinTable(img = imgObj, user = User.objects.get(username = request.user.username))
            jtObj.save()
            logger.info("Created a record in Join Table")

            return redirect('gallery:showImage', img_uid)


def showImage(request, img_uid):
    imageObject, userObject = None, None
    try:
        imageObject = Image.objects.get(img_uid = img_uid)
        userObject = JoinTable.objects.get(img = imageObject).user
    except Exception as exp:
        return HttpResponse(status = 404)
        logger.error(f"Caught an exception: {exp}")

    canDelete = request.user and request.user.is_authenticated and request.user.username == userObject.username
    if request.method == 'DELETE':
        logger.info("Delete Request")
        if not canDelete:
            return HttpResponse(status = 401)
        imageObject.delete()
        logger.info("Deleted Image Object")
        
        res = AwsManager.delete_file(img_uid + '.png')
        logger.info(f"Deleted Image from S3: {res}")
        
        if not res: return HttpResponse(status = 402)
        return HttpResponse(status = 204)

    
    context = {
        'imageObject': imageObject,
        'AWS_STORAGE_BUCKET_URL': settings.AWS_STORAGE_BUCKET_URL, 
        'disableDelete': 'disabled' if not canDelete else ''  ,
    }
   
    return render(request, 'gallery/showImage.html', context)
    

picaso/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

import logging
logger = logging.getLogger('watchtower-logger')

def home(request):
    return render(request, 'picaso/home.html')

@login_required(login_url='/', redirect_field_name=None)
def logout_view(request):
    if request.method != 'POST':
        logger.error(f"Request method is not POST for Logout View. Got {request.method}")
        return HttpResponse(status=405)
    logout(request)
    return redirect(request.META['HTTP_REFERER'])

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    {% block extraHead %}{% endblock %}
  </head>
  <body>
    <!-- Nav Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% block navItems %}{% endblock %}
          </div>
        </div>
      </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% block extraBody %}{% endblock %}
  </body>
</html>

templates/gallery/showGallery.html
{% extends "../base.html" %}

{% load static %}
{%load crispy_forms_tags %} 

{% block title %}Gallery{% endblock %}
{% block extraHead %}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<link rel="stylesheet" href="{% static 'gallery/showGallery.css' %}">
<script src="{% static 'gallery/autoSlot.js' %}"></script>
{% endblock %}

{% block navItems %}
<a class="btn btn-outline-dark bg-light" style="text-transform:none" href="/">Home</a>
{% if user.is_authenticated %}
    {% include '../logout_form.html' %}
{% else %}
    {% include '../login_form.html' %}
{% endif %}
{% endblock %}

{% block content %}

{% if not bypassOpenAISwitch %}
<div class="d-flex justify-content-center p-2">
    <form action="{% url 'gallery:showGallery' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="text-center">
            <input type="submit" value="Submit">
        </div>
        
    </form>
</div>
{% else %}
<p class="h3 text-center">
    Sorry for the inconvenience! Open AI Image generation has been disabled due to Exceeded qouta!
</p>
{% endif %}

<!-- Gallery -->
{% if imageObjects %}
<div class="container page-top">
    <div class="row">
        {% for imageObject in imageObjects %}
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a href="{% url 'gallery:showImage' imageObject.img_uid %}" class="fancybox" rel="ligthbox">
                    <img  src="{{ AWS_STORAGE_BUCKET_URL }}{{ imageObject.img_uid }}.png" class="zoom img-fluid" alt="">
                </a>
            </div>
        {% endfor %}
    </div>
<div>
{% endif %}

{% endblock %}
{% block extraBody %}

{% endblock %}

templates/gallery/showImage.html
{% extends "../base.html" %}
{% block title %}Image {{ imageObject.img_uid }}{% endblock %}
{% block extraHead %}
<style>
    button:disabled {
        cursor: not-allowed;
        pointer-events: all !important;
    }
</style>
{% endblock %}

{% block navItems %}
<a class="btn btn-outline-dark bg-light" style="text-transform:none" href="/">Home</a>
<a class="btn btn-outline-dark bg-light" style="text-transform:none" href="{% url 'gallery:showGallery' %}">Gallery</a>
{% if user.is_authenticated %}
    {% include '../logout_form.html' %}
{% else %}
    {% include '../login_form.html' %}
{% endif %}
{% endblock %}

{% block content %}
<div class="text-center p-2">
    <img src="{{ AWS_STORAGE_BUCKET_URL }}{{ imageObject.img_uid }}.png" class="img-fluid center">
</div>
<div class="text-center p-2">
    <p>{{ imageObject.img_prompt }}</p>
</div>
<div class="text-center p-2">
    <button onclick="makeDeleteRequest()" class="btn btn-secondary" {{ disableDelete }}>Delete</button>    
</div>
<div class="text-center p-2">
    <a class="btn btn-danger" role="button" href="{{ AWS_STORAGE_BUCKET_URL }}{{ imageObject.img_uid }}.png" download="{{ imageObject.img_uid }}.png">Open Image</a>
</div>
<script>
    function makeDeleteRequest(){
        let url = "{% url 'gallery:showImage' imageObject.img_uid %}"
        let options = {
            method: "DELETE",
            headers: { 
                credentials: 'same-origin',
                "X-CSRFToken": '{{csrf_token}}', 
            },
        }
        fetch(url, options)
        .then(response => {
            if(response.status == 204){
                alert("Image {{ imageObject.img_uid }} Deleted Successfully!");
                window.location.href = "{% url 'gallery:showGallery' %}";

            }else if(response.status == 401){
                alert("Cannot delete Image {{ imageObject.img_uid }}. Not authenticated!");
            }else if(response.status == 402){
                alert("Failed to delete Image {{ imageObject.img_uid }} from S3 bucket");
            }else{
                alert("Image {{ imageObject.img_uid }} failed to delete!");
            }
        })
    }
</script>
{% endblock %}

templates/login_form.html
{% load socialaccount %}

<form action="{% provider_login_url 'google' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-dark bg-light" style="text-transform:none">
        <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
        Login
    </button>
</form>

templates/logout_form.html
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-dark bg-light" style="text-transform:none">
        Logout
    </button>
</form>

templates/picaso/home.html
{% extends "../base.html" %}
{% block title %}Picaso{% endblock %}

{% block navItems %}
    <a class="btn btn-outline-dark bg-light" style="text-transform:none" href="{% url 'gallery:showGallery' %}">Gallery</a>
{% if user.is_authenticated %}
    {% include '../logout_form.html' %}
{% else %}
    {% include '../login_form.html' %}
</a>
{% endif %}
{% endblock %}

{% block content %}
<p class="h3">
    Picaso Image Generator
</p>
<p class="h4">
    Open AI's DALL-E Image Generator to produce perfectly modelled images from a text prompt
</p>

{% endblock %}